[package]
name = "rpc"
version = "0.1.0"
authors = ["Ethcore <admin@ethcore.io>"]

[lib]

[dependencies]
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rustc-hex = "2"

serialization = { path = "../serialization" }
chain = { path = "../chain" }
primitives = { path = "../primitives" }
keys = { path = "../keys" }
script = { path = "../script" }